### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' while using get_bookmarks

### ISSUE THREAD

**Issue by carlosrobles** [GGyll/audible-bookmark-extractor#15]
reproduction steps:

`authenticate  `
`list_books `
`download_books `
downloaded book with id 1 successfully (https://www.audible.co.uk/pd/The-Five-Dysfunctions-of-a-Team-Audiobook/B004EXKC5M)
`convert_audiobook` 
converted book with id 1 successfully. 
`get_bookmarks`

```
Traceback (most recent call last):
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 626, in <module>
    loop.run_until_complete(audible_obj.main())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 123, in main
    await self.enter_command()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 146, in enter_command
    await getattr(self, f"cmd_{command}", self.invalid_command_callback)(**_kwargs)
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 289, in cmd_help
    await self.main()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 123, in main
    await self.enter_command()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 146, in enter_command
    await getattr(self, f"cmd_{command}", self.invalid_command_callback)(**_kwargs)
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 461, in cmd_convert_audiobook
    await self.main()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 123, in main
    await self.enter_command()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 146, in enter_command
    await getattr(self, f"cmd_{command}", self.invalid_command_callback)(**_kwargs)
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 461, in cmd_convert_audiobook
    await self.main()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 123, in main
    await self.enter_command()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 146, in enter_command
    await getattr(self, f"cmd_{command}", self.invalid_command_callback)(**_kwargs)
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 289, in cmd_help
    await self.main()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 123, in main
    await self.enter_command()
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 146, in enter_command
    await getattr(self, f"cmd_{command}", self.invalid_command_callback)(**_kwargs)
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 375, in cmd_get_bookmarks
    print(self.get_bookmarks(book))
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlosrobles/Downloads/audible-bookmark-extractor-main/main_file.py", line 396, in get_bookmarks
    li_bookmarks = library.json().get("payload").get("records")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by gostak-dd** [comment]
Ah this should be a safe lookup which I will fix, but for your issue, can you print library.json() to see if it gives any clues? I can't access this particular book without buying it

**Comment by gostak-dd** [comment]
Are you sure you have bookmarks for this book?

**Comment by carlosrobles** [comment]
Thanks for the quick response.

`library.json()` is `{}` because `library` is a 404. 
 i do have bookmarks. 
 i think i understand the situation. 
`bookmarks_url = f"https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar?type=AUDI&key={asin}"` is using always `.com`, while im using audible in `.co.uk`
if I use an ASIN  for example 147359202X which exists in both [UK](https://www.audible.co.uk/pd/foo/147359202X) and [US](https://www.audible.com/pd/foo/147359202X), the response is correct. But for the example above i was using the ASIN [B004EXKC5M](https://www.audible.co.uk/pd/The-Five-Dysfunctions-of-a-Team-Audiobook/B004EXKC5M) that exists in UK but not in US, so bookmarks_url returns 404.

I didn't find any documentation about an equivalent bookmarks_url for UK, or headers/parameters to be send to the generic one, so not sure how to move forward from here. I will take a look, if you have an idea please let me know and I will be happy  to try and to send a pull request if i make it work.

Thanks!

**Comment by carlosrobles** [comment]
I found a workaround to save the day using a response with the bookmarks from https://www.audible.co.uk/webplayer. Got the JSON, hardcoded it in main_file.py, and adapted the logic later to use that response structure which is different. With this I made it work for both get_bookmarks, and also transcribe_bookmarks worked well after. Of course it is a dirty solution just to give me what i need for this book.

**Comment by gostak-dd** [comment]
> Thanks for the quick response.
> 
> `library.json()` is `{}` because `library` is a 404. i do have bookmarks. i think i understand the situation. `bookmarks_url = f"https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar?type=AUDI&key={asin}"` is using always `.com`, while im using audible in `.co.uk` if I use an ASIN for example 147359202X which exists in both [UK](https://www.audible.co.uk/pd/foo/147359202X) and [US](https://www.audible.com/pd/foo/147359202X), the response is correct. But for the example above i was using the ASIN [B004EXKC5M](https://www.audible.co.uk/pd/The-Five-Dysfunctions-of-a-Team-Audiobook/B004EXKC5M) that exists in UK but not in US, so bookmarks_url returns 404.


I would imagine everything is hosted on a server with the dot com domain. Did you try changing the url to .co.uk and see if it works then?

**Comment by gostak-dd** [comment]
Closing this due to lack of response
