### ISSUE TITLE
pydub can't handle files >4GB

### ISSUE THREAD

**Issue by funwithzaps** [GGyll/audible-bookmark-extractor#20]
Hey, first, let me thank you immensely for developing this tool.  I have no clue how to program and I'm hoping this tool is going to save me alot of time trying to prepare my presentations for my book club.

I tried running it on The Complete Essays of Michel de Montaigne, and got an error after the get_bookmarks command:  pydub.exceptions.CouldntDecodeError: Unable to process >4GB files

Any thought on how this could be dealt with?  Thanks for looking into it.

**Comment by gostak-dd** [comment]
Looks like pydub cannot load more than that into memory. The audio file needs to be split up.

https://github.com/Tikhvinskiy/Smart-audio-splitter

This might do the trick.
Give me a week or so and I could implement this

**Comment by gostak-dd** [comment]
Won't have time for a while to fix.

Issue is open for anyone that would like to incorporate Smart audio splitter into the program

**Comment by gostak-dd** [comment]
@MugunthKumar @jeromedalbert @HacDan

**Comment by rcrcr-omni** [comment]
I'm encountering this issue even with mp3 files that aren't >4GB but are ~17 hours long. I think it might be an AudioSegment issue. 

`Traceback (most recent call last):
  File "/Users/charlie/Library/Mobile Documents/com~apple~CloudDocs/projects/audible-extractor/main.py", line 13, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/charlie/Library/Mobile Documents/com~apple~CloudDocs/projects/audible-extractor/main.py", line 8, in main
    await cmd.command_loop()
  File "/Users/charlie/Library/Mobile Documents/com~apple~CloudDocs/projects/audible-extractor/command.py", line 87, in command_loop
    await self.command_loop()
  File "/Users/charlie/Library/Mobile Documents/com~apple~CloudDocs/projects/audible-extractor/command.py", line 85, in command_loop
    await getattr(self.audible_obj, f"cmd_{command}", self.invalid_command_callback)(**_kwargs)
  File "/Users/charlie/Library/Mobile Documents/com~apple~CloudDocs/projects/audible-extractor/audible_api.py", line 245, in cmd_get_bookmarks
    print(self.get_bookmarks(book))
  File "/Users/charlie/Library/Mobile Documents/com~apple~CloudDocs/projects/audible-extractor/audible_api.py", line 274, in get_bookmarks
    audio_book = AudioSegment.from_mp3(
  File "/Users/charlie/Library/Python/3.9/lib/python/site-packages/pydub/audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "/Users/charlie/Library/Python/3.9/lib/python/site-packages/pydub/audio_segment.py", line 778, in from_file
    fix_wav_headers(p_out)
  File "/Users/charlie/Library/Python/3.9/lib/python/site-packages/pydub/audio_segment.py", line 142, in fix_wav_headers
    raise CouldntDecodeError("Unable to process >4GB files")
pydub.exceptions.CouldntDecodeError: Unable to process >4GB files`

**Comment by gostak-dd** [comment]
@rcrcr-omni I haven't run into this problem, could you try updating pydub to the latest version and see if that changes anything?

**Comment by rcrcr-omni** [comment]
That would have been a simpler solution... I ended up rewriting the clip function to use FFMPEG which solved the issue.

**Comment by gostak-dd** [comment]
hm could you provide the code in case anyone else has this problem?

**Comment by rcrcr-omni** [comment]
Sure! Here it is. 

```
import subprocess
import re
```

```
def get_bookmarks(self, book):
        asin = book.get("asin")
        _title = book.get("title", {}).get("title", 'untitled')
        if not _title:
            return

        title = _title.lower().replace(" ", "_")

        bookmarks_url = f"https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar?type=AUDI&key={asin}"
        print(f"Getting bookmarks for {_title}")
        with audible.Client(auth=self.auth, response_callback=self.bookmark_response_callback) as client:
            library = client.get(
                bookmarks_url,
                num_results=1000,
                response_groups="product_desc, product_attrs"
            )

            li_bookmarks = library.json().get("payload", {}).get("records", [])
            li_clips = sorted(
                li_bookmarks, key=lambda i: int(i["startPosition"]), reverse=False)

            title_dir_path = os.path.join(artifacts_root_directory, "audiobooks", title)
            title_aax_path = os.path.join(title_dir_path, f"{title}.aax")
            title_m4b_path = os.path.join(title_dir_path, f"{title}.m4b")
            title_mp3_path = os.path.join(title_dir_path, f"{title}.mp3")

            file_counter = 1
            notes_dict = {}

            # Check whether a folder in clips/ for the book exists or not
            clips_dir_path = os.path.join(artifacts_root_directory, "audiobooks", title, "clips")
            path_exists = os.path.exists(clips_dir_path)
            if not path_exists:
                os.makedirs(clips_dir_path)

            # Extract a clip from MP3 file using ffmpeg without loading the full file into memory (as the AudioSegment method did)
            def extract_clip(input_mp3, start_ms, end_ms, output_path):
                start_sec = start_ms / 1000
                end_sec = end_ms / 1000

                command = [
                    "ffmpeg",
                    "-i", input_mp3,
                    "-ss", str(start_sec),
                    "-to", str(end_sec),
                    "-c:a", "flac",
                    output_path
                ]
                
                subprocess.run(command, check=True)
            
            # function to strip problematic characters from notes
            def sanitize_filename(filename):
                return re.sub(r'[<>:"/\\|?*]', '', filename) 
            
            # holder for tracking which clips have been processed
            processed_clips = set()
            for audio_clip in li_clips:
                # Get start position to slice
                raw_start_pos = int(audio_clip["startPosition"])

                # If we have a note then we save it so we can use it as the title for the bookmark text
                 if audio_clip.get("type", None) in ["audible.note"]:
                    notes_dict[raw_start_pos] = audio_clip.get("text")
                    print(
                        f"CLIP: {notes_dict[raw_start_pos]}  {raw_start_pos}")

                if audio_clip.get("type") in ["audible.clip", "audible.bookmark"]:
                    # check if the clip starts at the same place as a previous clip. If so, get rid. 
                    if raw_start_pos in processed_clips:
                        continue  

                    processed_clips.add(raw_start_pos)

                    start_pos = raw_start_pos - START_POSITION_OFFSET
                    end_pos = int(audio_clip.get("endPosition", raw_start_pos + 30000)) + END_POSITION_OFFSET
                    if start_pos == end_pos:
                        end_pos += 30000

                    file_name = notes_dict.get(raw_start_pos, f"clip{file_counter}")

                    clip_path = os.path.join(clips_dir_path, f"{sanitize_filename(file_name)}.flac")

                    extract_clip(title_mp3_path, start_pos, end_pos, clip_path)
                    file_counter += 1
```

**Comment by kamil-rudnicki** [comment]
Also had this issue, another way to fix: https://github.com/kamil-rudnicki/audible-bookmark-extractor/commit/3a5c724826ebe48398df84b7207f2c2003bda303

The code is 

- Loading the entire MP3 file into memory with AudioSegment.from_mp3()
- Then slicing it to create clips

The problem is that pydub's MP3 loading through ffmpeg can have issues with large files. The error message about "4GB files" is actually a pydub bug - it's happening in the WAV header fixing step. The solution is to use ffmpeg directly to extract audio segments instead of loading the entire file into memory.
